/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026-present The CortenaOS Project
 */
package framework.cortena.icons

/**
 * Identifies which Phosphor font weight an icon glyph belongs to.
 *
 * Each weight maps to a separately bundled TTF inside the library. Consumers never need to
 * reference a [PhosphorIconWeight] directly: it travels with the glyph constant exposed by
 * [PhosphorIcons].
 */
enum class PhosphorIconWeight {
    Regular,
    Bold,
    Light,
    Fill,
    Duotone,
    Thin,
}

/**
 * A single Phosphor icon glyph: the Unicode code point that draws it plus the font weight that owns
 * it. Generated by `scripts/generate_phosphor_icons.py`.
 */
data class PhosphorGlyph(val code: String, val weight: PhosphorIconWeight)
